site_name: Free Iran Proxy
use_directory_urls: false

theme:
  name: material
  lang: en
plugins:
  - search
#  - with-pdf
#  - enumerate-headings:
#      strict: false
#      toc_depth: 6
markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 6
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - 1. Introduction: index.md
  - 2. Windows: windows.md
  - 3. Android: android.md
  - 4. iOS: ios.md
  - 5. macOS: macos.md
  - 6. Troubleshooting: faq.md

