site_name: Free Iran Proxy
use_directory_urls: false

theme:
  name: material
  lang: en
  features:
    - navigation.sections
plugins:
  - search
#  - with-pdf
#  - enumerate-headings:
#      strict: false
#      toc_depth: 6
markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 6
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
  - Introduction: index.md
  - Client Guides: guides.md
  - Guides:
    - Windows: windows.md
    - Android: android.md
    - iOS: ios-nv.md
    - macOS: macos.md
  - Troubleshooting:
    - FAQ: faq.md

