site_name: Free Iran Proxy
use_directory_urls: true

theme:
  name: material
  lang: en
  favicon: fontawesome/solid/globe
  icon:
   logo: fontawesome/solid/globe
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - content.tabs.link
    - toc.integrate
    - announce.dismiss
  custom_dir: overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
markdown_extensions:
  - toc:
      permalink: "#"
      toc_depth: 6
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html

nav:
  - Introduction:
    - Overview: index.md
  - Client Guides:
    - Overview: guides.md
  - Devices:
    - Windows: windows.md
    - Android: android.md
    - iOS: ios.md
    - macOS: macos.md
  - Troubleshooting:
    - FAQ: faq.md


extra:
  generator: false